server:
  port: 9011
spring:
  application:
    name: spring-boot-data-jpa
  datasource:
    platform: mysql                        # 指定数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bobandata123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.172.246.234:3306/zhouyf?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
