server:
  port: 8882
#  servlet:
#    session:
#      timeout: 61
spring:
  application:
    name: security-swagger
  datasource:
    platform: mysql                        # 指定数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vuzk@6108
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.56:3306/security-swagger?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true